In [2]:
import numpy as np
import pandas as pd

In [5]:
dataset = pd.read_csv('Ionosphere.csv')

In [6]:
dataset.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g

In [8]:
dataset.tail()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307,g
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712,g
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577,g
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243,g
350,1,0,0.84710,0.13533,0.73638,-0.06151,0.87873,0.08260,0.88928,-0.09139,...,-0.15114,0.81147,-0.04822,0.78207,-0.00703,0.75747,-0.06678,0.85764,-0.06151,g

In [9]:
dataset.describe()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature25,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34
count,351.000000,351.0,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,...,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000
mean,0.891738,0.0,0.641342,0.044372,0.601068,0.115889,0.550095,0.119360,0.511848,0.181345,...,0.396135,-0.071187,0.541641,-0.069538,0.378445,-0.027907,0.352514,-0.003794,0.349364,0.014480
std,0.311155,0.0,0.497708,0.441435,0.519862,0.460810,0.492654,0.520750,0.507066,0.483851,...,0.578451,0.508495,0.516205,0.550025,0.575886,0.507974,0.571483,0.513574,0.522663,0.468337
min,0.000000,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,1.000000,0.0,0.472135,-0.064735,0.412660,-0.024795,0.211310,-0.054840,0.087110,-0.048075,...,0.000000,-0.332390,0.286435,-0.443165,0.000000,-0.236885,0.000000,-0.242595,0.000000,-0.165350
50%,1.000000,0.0,0.871110,0.016310,0.809200,0.022800,0.728730,0.014710,0.684210,0.018290,...,0.553890,-0.015050,0.708240,-0.017690,0.496640,0.000000,0.442770,0.000000,0.409560,0.000000
75%,1.000000,0.0,1.000000,0.194185,1.000000,0.334655,0.969240,0.445675,0.953240,0.534195,...,0.905240,0.156765,0.999945,0.153535,0.883465,0.154075,0.857620,0.200120,0.813765,0.171660
max,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   feature1   351 non-null    int64
 1   feature2   351 non-null    int64
 2   feature3   351 non-null    float64
 3   feature4   351 non-null    float64
 4   feature5   351 non-null    float64
 5   feature6   351 non-null    float64
 6   feature7   351 non-null    float64
 7   feature8   351 non-null    float64
 8   feature9   351 non-null    float64
 9   feature10  351 non-null    float64
 10  feature11  351 non-null    float64
 11  feature12  351 non-null    float64
 12  feature13  351 non-null    float64
 13  feature14  351 non-null    float64
 14  feature15  351 non-null    float64
 15  feature16  351 non-null    float64
 16  feature17  351 non-null    float64
 17  feature18  351 non-null    float64
 18  feature19  351 non-null    float64
 19  feature20  351 non-null    float64
 20  feature21  351 non-null    float64
 21  feature22  351 non-null    float64
 22  feature23  351 non-null    float64
 23  feature24  351 non-null    float64
 24  feature25  351 non-null    float64
 25  feature26  351 non-null    float64
 26  feature27  351 non-null    float64
 27  feature28  351 non-null    float64
 28  feature29  351 non-null    float64
 29  feature30  351 non-null    float64
 30  feature31  351 non-null    float64
 31  feature32  351 non-null    float64
 32  feature33  351 non-null    float64
 33  feature34  351 non-null    float64
 34  label      351 non-null    object
dtypes: float64(32), int64(2), object(1)
memory usage: 96.1+ KB

In [11]:
dataset.isnull().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

In [12]:
dataset.isna().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

In [13]:
dataset.feature2

0      0
1      0
2      0
3      0
4      0
      ..
346    0
347    0
348    0
349    0
350    0
Name: feature2, Length: 351, dtype: int64

In [14]:
# feature2 has 0 values, it's useless for the data so will drop this
dataset.drop(columns='feature2', inplace=True)

In [15]:
dataset.head(20)

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
0,1,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,0.85243,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,0.50874,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,0.73082,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,0.52798,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g
5,1,0.02337,-0.00592,-0.09924,-0.11949,-0.00763,-0.11824,0.14706,0.06637,0.03786,...,-0.01535,-0.03240,0.09223,-0.07859,0.00732,0.00000,0.00000,-0.00039,0.12011,b
6,1,0.97588,-0.10602,0.94601,-0.20800,0.92806,-0.28350,0.85996,-0.27342,0.79766,...,-0.81634,0.13659,-0.82510,0.04606,-0.82395,-0.04262,-0.81318,-0.13832,-0.80975,g
7,0,0.00000,0.00000,0.00000,0.00000,1.00000,-1.00000,0.00000,0.00000,-1.00000,...,1.00000,1.00000,1.00000,0.00000,0.00000,1.00000,1.00000,0.00000,0.00000,b
8,1,0.96355,-0.07198,1.00000,-0.14333,1.00000,-0.21313,1.00000,-0.36174,0.92570,...,-0.65440,0.57577,-0.69712,0.25435,-0.63919,0.45114,-0.72779,0.38895,-0.73420,g
9,1,-0.01864,-0.08459,0.00000,0.00000,0.00000,0.00000,0.11470,-0.26810,-0.45663,...,-0.01326,0.20645,-0.02294,0.00000,0.00000,0.16595,0.24086,-0.08208,0.38065,b
10,1,1.00000,0.06655,1.00000,-0.18388,1.00000,-0.27320,1.00000,-0.43107,1.00000,...,-0.89128,0.47211,-0.86500,0.40303,-0.83675,0.30996,-0.89093,0.22995,-0.89158,g
11,1,1.00000,-0.54210,1.00000,-1.00000,1.00000,-1.00000,1.00000,0.36217,1.00000,...,-0.40888,1.00000,-0.62745,1.00000,-1.00000,1.00000,-1.00000,1.00000,-1.00000,b
12,1,1.00000,-0.16316,1.00000,-0.10169,0.99999,-0.15197,1.00000,-0.19277,0.94055,...,-0.47137,0.76224,-0.58370,0.65723,-0.68794,0.68714,-0.64537,0.64727,-0.67226,g
13,1,1.00000,-0.86701,1.00000,0.22280,0.85492,-0.39896,1.00000,-0.12090,1.00000,...,-0.17012,1.00000,0.35924,1.00000,-0.66494,1.00000,0.88428,1.00000,-0.18826,b
14,1,1.00000,0.07380,1.00000,0.03420,1.00000,-0.05563,1.00000,0.08764,1.00000,...,0.20033,1.00000,0.36743,0.95603,0.48641,1.00000,0.32492,1.00000,0.46712,g
15,1,0.50932,-0.93996,1.00000,0.26708,-0.03520,-1.00000,1.00000,-1.00000,0.43685,...,0.92236,0.39752,0.26501,0.00000,0.00000,1.00000,0.23188,0.00000,0.00000,b
16,1,0.99645,0.06468,1.00000,-0.01236,0.97811,0.02498,0.96112,0.02312,0.99274,...,0.13412,0.79476,0.13638,0.79110,0.15379,0.77122,0.15930,0.70941,0.12015,g
17,0,0.00000,0.00000,-1.00000,-1.00000,1.00000,1.00000,-1.00000,1.00000,-1.00000,...,1.00000,1.00000,-1.00000,-1.00000,1.00000,-1.00000,-1.00000,1.00000,-1.00000,b
18,1,0.67065,0.02528,0.66626,0.05031,0.57197,0.18761,0.08776,0.34081,0.63621,...,0.23724,0.46167,0.24618,0.43433,0.25306,0.40663,0.25792,1.00000,0.33036,g
19,0,1.00000,-1.00000,0.00000,0.00000,0.00000,0.00000,1.00000,1.00000,1.00000,...,1.00000,1.00000,1.00000,1.00000,-1.00000,1.00000,1.00000,1.00000,1.00000,b

In [16]:
dataset.label.value_counts()

g    225
b    126
Name: label, dtype: int64

In [17]:
# so here we will encode label column, b=1 and g=0
replace_values = {'label':{'g':0, 'b':1}}

In [18]:
dataset = dataset.replace(replace_values)

In [19]:
dataset = dataset.sample(frac=1)

In [20]:
dataset

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
65,1,0.84783,0.10598,1.00000,0.39130,1.00000,-1.00000,0.66938,0.08424,1.00000,...,-0.33333,1.00000,0.15942,0.37681,-0.01947,1.00000,0.22464,1.00000,0.37409,1
207,1,0.47368,-0.10526,0.83781,0.01756,0.83155,0.02615,0.68421,-0.05263,0.68421,...,0.21053,0.65419,0.08968,0.52632,-0.21053,0.60150,0.09534,0.57418,0.09719,0
125,1,0.95217,0.06595,0.93614,0.13030,0.90996,0.19152,0.84881,-0.49962,0.90023,...,0.44199,0.34374,0.43221,0.90330,1.00000,0.23405,0.39620,0.18632,0.37191,0
308,1,0.75564,0.49638,0.83550,0.54301,0.54916,0.72063,0.35225,0.70792,0.13469,...,-0.29099,-0.70352,-0.32792,-0.63312,-0.19185,-0.34131,-0.60454,-0.19609,-0.62956,0
82,1,0.92277,0.07804,0.92679,0.16251,0.89702,0.24618,0.84111,0.35197,0.78801,...,0.76146,0.18765,0.73885,0.09694,0.71038,0.02735,0.77072,-0.04023,0.69509,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,1,1.00000,-0.06604,1.00000,0.62937,1.00000,0.09557,1.00000,0.20280,1.00000,...,-0.58042,1.00000,-0.81372,1.00000,-1.00000,1.00000,-0.78555,1.00000,-0.48252,0
261,1,0.79830,0.09417,0.78129,0.20656,0.71628,0.28068,0.69320,0.41252,0.65917,...,0.63183,-0.11925,0.60696,-0.18226,0.56015,-0.25516,0.51701,-0.27339,0.42467,0
13,1,1.00000,-0.86701,1.00000,0.22280,0.85492,-0.39896,1.00000,-0.12090,1.00000,...,-0.17012,1.00000,0.35924,1.00000,-0.66494,1.00000,0.88428,1.00000,-0.18826,1
93,1,-0.54180,0.14861,-0.33746,0.73375,0.52012,-0.13932,0.31889,-0.06811,0.20743,...,0.65635,0.41348,-0.40116,-0.15170,0.11146,0.02399,0.55820,0.52632,-0.08978,1
129,1,0.96933,0.00876,1.00000,0.00843,0.98658,-0.00763,0.97868,-0.02844,0.99820,...,-0.04527,0.99188,-0.03473,0.97020,-0.02478,1.00000,-0.03855,0.98420,-0.04112,0

In [21]:
y = dataset.label
x = dataset.drop(columns='label')

In [22]:
x.head()

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature25,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34
65,1,0.84783,0.10598,1.00000,0.39130,1.00000,-1.00000,0.66938,0.08424,1.00000,...,0.91033,-0.33333,1.00000,0.15942,0.37681,-0.01947,1.00000,0.22464,1.00000,0.37409
207,1,0.47368,-0.10526,0.83781,0.01756,0.83155,0.02615,0.68421,-0.05263,0.68421,...,0.42105,0.21053,0.65419,0.08968,0.52632,-0.21053,0.60150,0.09534,0.57418,0.09719
125,1,0.95217,0.06595,0.93614,0.13030,0.90996,0.19152,0.84881,-0.49962,0.90023,...,0.40440,0.44199,0.34374,0.43221,0.90330,1.00000,0.23405,0.39620,0.18632,0.37191
308,1,0.75564,0.49638,0.83550,0.54301,0.54916,0.72063,0.35225,0.70792,0.13469,...,-0.98988,-0.29099,-0.70352,-0.32792,-0.63312,-0.19185,-0.34131,-0.60454,-0.19609,-0.62956
82,1,0.92277,0.07804,0.92679,0.16251,0.89702,0.24618,0.84111,0.35197,0.78801,...,0.23693,0.76146,0.18765,0.73885,0.09694,0.71038,0.02735,0.77072,-0.04023,0.69509

In [23]:
y

65     1
207    0
125    0
308    0
82     0
      ..
80     0
261    0
13     1
93     1
129    0
Name: label, Length: 351, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size= 0.4 )

In [26]:
X_train

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature25,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34
52,1,1.00000,1.00000,1.00000,1.00000,0.91010,1.00000,-0.26970,1.00000,-0.83152,...,0.90014,-1.00000,1.00000,-1.00000,1.00000,-1.00000,1.00000,-0.34686,1.00000,0.34845
260,1,0.50000,0.00000,0.38696,0.10435,0.49130,0.06522,0.46957,-0.03913,0.35652,...,0.47391,-0.00870,0.41789,0.06908,0.38696,0.03913,0.35217,0.14783,0.44783,0.17391
151,1,0.60000,0.03333,0.63333,0.06667,0.70000,0.06667,0.70000,0.00000,0.63333,...,0.63333,0.13333,0.65932,0.10168,0.60000,0.13333,0.60000,0.16667,0.63333,0.16667
337,1,0.90147,0.41786,0.64131,0.75725,0.30440,0.95148,-0.20449,0.96534,-0.55483,...,0.44483,-0.82154,0.74105,-0.55231,0.89415,-0.18725,0.87893,0.20359,0.70555,0.54852
272,1,0.63510,-0.04388,0.76530,0.02968,0.61432,0.36028,0.65358,-0.00462,0.64203,...,0.64665,0.23095,0.68775,0.17704,0.61663,0.07621,0.66316,0.19841,0.69053,0.36721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,1,0.61857,0.10850,0.70694,-0.06935,0.70358,0.01678,0.74273,0.00224,0.71029,...,0.71253,-0.09508,0.69845,-0.01673,0.63311,0.04810,0.78859,-0.05145,0.65213,-0.04698
60,1,1.00000,0.09771,1.00000,0.12197,1.00000,0.22574,0.98602,0.09237,0.94930,...,0.76193,0.34658,0.68452,0.42746,0.62764,0.46031,0.56791,0.47033,0.54252,0.50903
175,1,1.00000,0.11765,1.00000,0.23529,1.00000,0.41176,1.00000,0.05882,1.00000,...,1.00000,-0.11765,1.00000,0.20225,1.00000,0.05882,1.00000,0.35294,1.00000,0.23529
72,1,0.96087,0.08620,0.96760,0.19279,0.96026,0.27451,0.98044,0.35052,0.92867,...,0.40615,0.74689,0.33401,0.83796,0.24944,0.86061,0.13756,0.86835,0.09048,0.86285
301,1,0.83367,0.31456,0.65541,0.57671,0.34962,0.70677,0.17293,0.78947,-0.18976,...,-0.26577,-0.66014,-0.01530,-0.69706,0.22708,-0.64428,0.43100,-0.51206,0.64662,-0.30075

In [27]:
Y_train

52     0
260    0
151    0
337    0
272    0
      ..
239    0
60     0
175    0
72     0
301    0
Name: label, Length: 210, dtype: int64

In [28]:
# Build The Model
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras import regularizers

In [29]:
network = Sequential()

In [30]:
network.add(layers.Dense(16, activation='relu', kernel_regularizer = regularizers.l2(0.001),  input_shape=(X_train.shape[1],)))
network.add(layers.Dense(8, activation='relu' , kernel_regularizer = regularizers.l2(0.001)))
network.add(layers.Dense(4, activation='relu' , kernel_regularizer = regularizers.l2(0.001)))
network.add(layers.Dense(1, activation='sigmoid'))

In [31]:
network.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')

In [32]:
network.fit(X_train, Y_train, epochs=60, batch_size=8)

Epoch 1/60
27/27 [==============================] - 2s 3ms/step - loss: 0.6499 - accuracy: 0.6685
Epoch 2/60
27/27 [==============================] - 0s 2ms/step - loss: 0.6409 - accuracy: 0.6298
Epoch 3/60
27/27 [==============================] - 0s 2ms/step - loss: 0.5885 - accuracy: 0.6811
Epoch 4/60
27/27 [==============================] - 0s 3ms/step - loss: 0.5765 - accuracy: 0.6441
Epoch 5/60
27/27 [==============================] - 0s 4ms/step - loss: 0.5749 - accuracy: 0.6246
Epoch 6/60
27/27 [==============================] - 0s 3ms/step - loss: 0.5758 - accuracy: 0.6878
Epoch 7/60
27/27 [==============================] - 0s 3ms/step - loss: 0.5499 - accuracy: 0.7976
Epoch 8/60
27/27 [==============================] - 0s 3ms/step - loss: 0.5764 - accuracy: 0.7897
Epoch 9/60
27/27 [==============================] - 0s 2ms/step - loss: 0.5394 - accuracy: 0.7902
Epoch 10/60
27/27 [==============================] - 0s 2ms/step - loss: 0.5033 - accuracy: 0.8623
Epoch 11/60
27/27 [==============================] - 0s 2ms/step - loss: 0.4703 - accuracy: 0.8704
Epoch 12/60
27/27 [==============================] - 0s 3ms/step - loss: 0.4509 - accuracy: 0.8585
Epoch 13/60
27/27 [==============================] - 0s 3ms/step - loss: 0.3988 - accuracy: 0.8852
Epoch 14/60
27/27 [==============================] - 0s 2ms/step - loss: 0.3806 - accuracy: 0.9054
Epoch 15/60
27/27 [==============================] - 0s 2ms/step - loss: 0.3837 - accuracy: 0.9184
Epoch 16/60
27/27 [==============================] - 0s 3ms/step - loss: 0.3649 - accuracy: 0.9240
Epoch 17/60
27/27 [==============================] - 0s 2ms/step - loss: 0.3703 - accuracy: 0.9174
Epoch 18/60
27/27 [==============================] - 0s 3ms/step - loss: 0.3543 - accuracy: 0.9206
Epoch 19/60
27/27 [==============================] - 0s 3ms/step - loss: 0.3125 - accuracy: 0.9598
Epoch 20/60
27/27 [==============================] - 0s 3ms/step - loss: 0.3404 - accuracy: 0.9414
Epoch 21/60
27/27 [==============================] - 0s 3ms/step - loss: 0.3293 - accuracy: 0.9675
Epoch 22/60
27/27 [==============================] - 0s 3ms/step - loss: 0.3136 - accuracy: 0.9605
Epoch 23/60
27/27 [==============================] - 0s 3ms/step - loss: 0.3308 - accuracy: 0.9569
Epoch 24/60
27/27 [==============================] - 0s 3ms/step - loss: 0.3189 - accuracy: 0.9549
Epoch 25/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2897 - accuracy: 0.9759
Epoch 26/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2632 - accuracy: 0.9834
Epoch 27/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2946 - accuracy: 0.9785
Epoch 28/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2638 - accuracy: 0.9748
Epoch 29/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2478 - accuracy: 0.9793
Epoch 30/60
27/27 [==============================] - 0s 2ms/step - loss: 0.2871 - accuracy: 0.9784
Epoch 31/60
27/27 [==============================] - 0s 2ms/step - loss: 0.2499 - accuracy: 0.9897
Epoch 32/60
27/27 [==============================] - 0s 2ms/step - loss: 0.2438 - accuracy: 0.9942
Epoch 33/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2540 - accuracy: 0.9891
Epoch 34/60
27/27 [==============================] - 0s 4ms/step - loss: 0.2645 - accuracy: 0.9956
Epoch 35/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2385 - accuracy: 0.9824
Epoch 36/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2017 - accuracy: 0.9993
Epoch 37/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2392 - accuracy: 0.9836
Epoch 38/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2426 - accuracy: 0.9945
Epoch 39/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2287 - accuracy: 0.9906
Epoch 40/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2064 - accuracy: 0.9995
Epoch 41/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2110 - accuracy: 0.9981
Epoch 42/60
27/27 [==============================] - 0s 2ms/step - loss: 0.2309 - accuracy: 0.9946
Epoch 43/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1942 - accuracy: 0.9993
Epoch 44/60
27/27 [==============================] - 0s 2ms/step - loss: 0.2078 - accuracy: 0.9973
Epoch 45/60
27/27 [==============================] - 0s 2ms/step - loss: 0.2009 - accuracy: 0.9989
Epoch 46/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1931 - accuracy: 0.9973
Epoch 47/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1928 - accuracy: 0.9959
Epoch 48/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2096 - accuracy: 0.9869
Epoch 49/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1849 - accuracy: 0.9940
Epoch 50/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1750 - accuracy: 0.9963
Epoch 51/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1756 - accuracy: 0.9995
Epoch 52/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1799 - accuracy: 0.9946
Epoch 53/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1914 - accuracy: 0.9973
Epoch 54/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1632 - accuracy: 0.9963
Epoch 55/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1798 - accuracy: 0.9934
Epoch 56/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1659 - accuracy: 0.9963
Epoch 57/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1528 - accuracy: 0.9906
Epoch 58/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1646 - accuracy: 0.9891
Epoch 59/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1615 - accuracy: 0.9963
Epoch 60/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1662 - accuracy: 0.9926

In [33]:
prediction = network.predict(X_test)

In [34]:
network.evaluate(X_test, Y_test)

5/5 [==============================] - 1s 3ms/step - loss: 0.4935 - accuracy: 0.8865

[0.49347713589668274, 0.8865247964859009]

In [35]:
prediction.shape

(141, 1)

In [36]:
prediction=prediction.reshape(141)

In [37]:
output = pd.DataFrame({'Actual': Y_test})

In [38]:
output['prediction'] = prediction

In [39]:
output.reset_index(inplace=True)

In [40]:
output

     index  Actual  prediction
0       68       0    0.000031
1      236       1    0.023356
2      201       0    0.014291
3       75       1    0.740629
4       12       0    0.000677
..     ...     ...         ...
136    167       0    0.000520
137    255       0    0.000135
138    342       0    0.002331
139     66       0    0.000932
140    256       0    0.004166

[141 rows x 3 columns]